Lecture 7 hw 3
ildarado12/react-20240705 pull request #12
Opened 2024-08-12 12:46 UTC by ildarado12

2024-08-12 13:33 UTC, zubkov7 requested changes

2024-08-12 13:33 UTC, zubkov7 commented on src/components/login-button/login-button.jsx
> +    return selectUserById(state, "a304959a-76c0-4b34-954a-b38dbf310360");
по конкретному айдишнику лучше никогда не селектить, данные могут измениться

если нужен захардкоженный пользователь, то лучше положить данные в константу

2024-08-12 13:33 UTC, zubkov7 commented on src/components/login-button/login-button.jsx
> +      <h4 className={value === "Login" ? styles.hidden : styles.user}>
лучше делать условный рендеринг, а не скрывать через стили

2024-08-12 13:33 UTC, zubkov7 commented on src/components/login-context/context.jsx
> +  const [user, setUser] = useState("Login");
переменная user не отражает по неймингу, что хранится в ней

тут больше подойдет loginStatus или что-то типо такого

2024-08-12 13:33 UTC, zubkov7 commented on src/components/restaurant/restaurant.jsx
> +              <li className={classNames(styles.card, styles.review)}>
нужно добавить key проп

2024-08-12 13:33 UTC, zubkov7 commented on src/components/restaurant/restaurant.jsx
> +              <li className={classNames(styles.card, styles.review)}>
нужно добавить key проп

2024-08-12 13:33 UTC, zubkov7 commented on src/components/restaurants-list/restaurants-list.jsx
> +        <li className={styles.restaurant}>
нужно добавить key проп

2024-08-12 14:33 UTC, zubkov7 commented on src/components/menu/menu.jsx
> +          <Ingredients ingredient={ingredient} key={ingredient} />
что лежит в ingredient? для key необходимо использовать id сущности

2024-08-12 15:30 UTC, ildarado12 commented on src/components/menu/menu.jsx
> +          <Ingredients ingredient={ingredient} key={ingredient} />
Исправил, посмотрите пожалуйста.

2024-08-13 11:18 UTC, zubkov7 approved these changes

2024-08-13 11:18 UTC, merged